title:        Master
url:          http://kin-lane.github.io/master/
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/master/blog/page:num"

production_url : http://kin-lane.github.io/master/

BASE_PATH : http://kin-lane.github.io/master/

categories_path : /categories.html
tags_path : /tags.html

org: Kin-Lane
repo: master
resource: Master
oauthio: qUDL4eZqKPFb41SwuWIYIwLR6jI